# 'xvlog' Params
# 'xvlog' Compiles and processes HDL files
XVLOG_PARAMS := --sv --incr --work $(WORK_LIB) \
                # --sourcelibdir $(MAKEFILE_DIR)src/packages \
                # --sourcelibdir ../src/modules \
                # --sourcelibdir ../src/packages \
                # --sourcelibdir ../test \
                # --sourcelibdir ../test/common

# 'xelab' Params
# 'xelab' Elaborates HDL designs and creates a binary simulation snapshot for use with xsim
XELAB_PARAMS := --debug all --uvm_version 1.2  -top $(TOP) -snapshot $(SNAPSHOT)

# 'xsim' Params
# 'xsim' Runs the snapshot generated by 'xelab'
XSIM_PARAMS  := --tclbatch $(MAKEFILE_DIR)scripts/tcl/xsim_cfg.tcl
XSIM_PARAMS_VERBOSE := --tl --tp
XSIM_VERBOSE := 0
ifeq ($(XSIM_VERBOSE),1)
	XSIM_PARAMS += $(XSIM_PARAMS_VERBOSE)
endif